# Generated by Django 4.0 on 2022-01-05 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_remove_customusermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='role',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='authapp.roles'),
        ),
    ]
