# Generated by Django 4.0 on 2022-01-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_roles_role_name_alter_customusermodel_role_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customusermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='is_staff',
        ),
        migrations.AlterField(
            model_name='customusermodel',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name=((1, 'Admin'), (2, 'Seller'), (3, 'Customer'))),
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
    ]
